---

vagrant_hostname: precise64-ansible.dev
vagrant_ip: 192.168.88.30
# Virtual machine memory setup.
vm_ram: "2048"

locale: en_US.UTF-8
language: 'en_US:en'
timezone: Etc/UTC

# Your local path for all sites.
local_sites_path: "~/VM/myproject/sites"
# Your VM local path for all sites.
vm_sites_path: "/var/www/sites"

# Your site index path.
site_root_path: "/var/www/sites/mysite/www"

# Database details.
mysql_root_password: root
db_name: mysite
db_user: mysite
db_password: mysite

# PHP settings.
php_max_execution_time: "128"
php_memory_limit: "512M"

# Drush.
drush_version: 7.*
