---

vagrant_hostname: precise64-ansible
# Virtual machine memory setup.
vm_ram: "2048"

locale: en_US.UTF-8
language: 'en_US:en'
timezone: Etc/UTC

# Your site root path.
site_root_path: "/var/www/site/www"

# Database details.
mysql_root_password: root
db_name: mysite
db_user: mysite
db_password: mysite

# PHP settings.
php_max_execution_time: "128"
php_memory_limit: "512M"

# Drush.
drush_version: 7.*
