---

- name: Install xdebug for PHP5.
  apt: name=php5-xdebug

# xdebug configuration extra line 1/6.
- lineinfile: dest=/etc/php5/apache2/conf.d/xdebug.ini
              line='xdebug.remote_enable=1'

# xdebug configuration extra line 2/6.
- lineinfile: dest=/etc/php5/apache2/conf.d/xdebug.ini
              line='xdebug.remote_port=9000'

# xdebug configuration extra line 3/6.
- lineinfile: dest=/etc/php5/apache2/conf.d/xdebug.ini
              line='xdebug.remote_autostart=1'

# xdebug configuration extra line 4/6.
- lineinfile: dest=/etc/php5/apache2/conf.d/xdebug.ini
              line='xdebug.remote_handler=dbgp'

# xdebug configuration extra line 5/6.
- lineinfile: dest=/etc/php5/apache2/conf.d/xdebug.ini
              line='xdebug.remote_mode=req'

# xdebug configuration extra line 6/6.
- lineinfile: dest=/etc/php5/apache2/conf.d/xdebug.ini
              line='xdebug.remote_connect_back=1'
