---
- name: Install MySQL server
  apt: name=mysql-server state=latest

- name: Install MySQL module for PHP
  apt: name=php5-mysql state=latest

- name: Ensure MySQL is started and enabled on boot.
  service: "name=mysql state=started enabled=yes"

- name: Install python-mysqldb for ansible command mysql_user.
  apt: name=python-mysqldb state=latest
