---
# Has to be after the root password assignment, for idempotency.
# - name: Copy .my.cnf file with root password credentials.
#   template:
#     src: "user-my.cnf.j2"
#     dest: "/root/.my.cnf"
#     owner: root
#     group: root
#     mode: 0600

- name: Install python-mysqldb for ansible command mysql_user.
  apt: name=python-mysqldb state=latest

- name: Copy user-my.cnf MySQL configuration.
  template:
    src: user-my.cnf.j2
    dest: "/root/.my.cnf"
    owner: root
    group: root
    mode: 0644
  notify: restart mysql

- name: Include local MySQL user.
  lineinfile: dest=/etc/mysql/my.cnf line="!include /root/.my.cnf"
  notify: restart mysql

# 'localhost' needs to be last for idempotency.
- name: Update MySQL root password for localhost root account.
  mysql_user:
    name: "root"
    password: "{{ mysql_root_password }}"
  # with_items: mysql_root_hosts.stdout_lines
